# Generated by Django 5.1.1 on 2025-11-16 21:52

import django.db.models.deletion
import markdownx.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_classconfig_profile_display_name_profile_role_in_soc'),
        ('diagrams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagram',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='diagram',
            name='fossflow_url',
        ),
        migrations.AddField(
            model_name='diagram',
            name='approved',
            field=models.BooleanField(default=False, help_text='Once approved+published, visible to the whole class.'),
        ),
        migrations.AddField(
            model_name='diagram',
            name='external_url',
            field=models.URLField(blank=True, help_text='Optional link to Lucidchart, draw.io, Excalidraw, etc.'),
        ),
        migrations.AddField(
            model_name='diagram',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='diagram',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagrams', to='accounts.team'),
        ),
        migrations.AddField(
            model_name='diagram',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='diagram',
            name='visibility',
            field=models.CharField(choices=[('team', 'Team only'), ('class', 'Class (published)'), ('global', 'Global/public')], default='team', max_length=10),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a PNG/JPG export of your diagram.', null=True, upload_to='diagrams/'),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='notes',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Describe the diagram, assumptions, data flows, etc. (Markdown).'),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagrams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
