# Generated by Django 5.1.1 on 2025-11-04 04:14

import django.db.models.deletion
import markdownx.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('IR', 'Incident Response'), ('AC', 'Access Control'), ('LM', 'Log Management'), ('CC', 'Change Control'), ('NW', 'Network Security'), ('BK', 'Backup & Recovery'), ('OT', 'Other')], default='OT', max_length=2)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', markdownx.models.MarkdownxField()),
                ('approved', models.BooleanField(default=False)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
    ]
