# Generated by Django 5.1.1 on 2025-11-16 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_classconfig_profile_display_name_profile_role_in_soc'),
        ('policies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='accounts.team'),
        ),
        migrations.AddField(
            model_name='policy',
            name='visibility',
            field=models.CharField(choices=[('team', 'Team-only'), ('class', 'Class-wide'), ('global', 'Public')], default='team', max_length=10),
        ),
        migrations.AlterField(
            model_name='policy',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='policy',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
