# Generated by Django 5.1.1 on 2025-11-13 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_classconfig_profile_display_name_profile_role_in_soc'),
        ('docs', '0002_doccategory_alter_docpage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docpage',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs', to='accounts.team'),
        ),
    ]
