# Generated by Django 5.1.1 on 2025-11-16 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_classconfig_profile_display_name_profile_role_in_soc'),
        ('docs', '0004_alter_docpage_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='docpage',
            name='visibility',
            field=models.CharField(choices=[('team', 'Team only'), ('class', 'Published to class')], default='team', max_length=10),
        ),
        migrations.AlterField(
            model_name='docpage',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Leave blank for instructor/global docs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs', to='accounts.team'),
        ),
    ]
