# Generated by Django 5.1.1 on 2025-11-04 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('milestone', 'student')},
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('max_points', models.PositiveIntegerField(default=10)),
                ('weight', models.FloatField(default=1.0)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='grading.milestone')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='grading.submission')),
            ],
        ),
        migrations.CreateModel(
            name='CriterionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField(default=0)),
                ('comment', models.TextField(blank=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.criterion')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_scores', to='grading.submission')),
            ],
            options={
                'unique_together': {('submission', 'criterion')},
            },
        ),
    ]
