# Generated by Django 5.1.1 on 2025-11-16 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_docpage_visibility_alter_docpage_team'),
        ('grading', '0003_team_submission_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='doc',
            field=models.ForeignKey(blank=True, help_text='Team documentation page used as the main write-up.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='docs.docpage'),
        ),
    ]
