# Generated by Django 5.1.1 on 2025-11-16 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_docpage_visibility_alter_docpage_team'),
        ('grading', '0004_submission_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='doc',
        ),
        migrations.AddField(
            model_name='submission',
            name='doc_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='docs.docpage'),
        ),
    ]
