# Generated by Django 5.1.1 on 2025-11-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_can_create_teams', models.BooleanField(default=True, help_text='If disabled, only staff can create/assign teams.')),
            ],
            options={
                'verbose_name': 'Class configuration',
                'verbose_name_plural': 'Class configuration',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='role_in_soc',
            field=models.CharField(blank=True, help_text="Student's role in the SOC (e.g., 'SIEM engineer', 'IR lead').", max_length=150),
        ),
    ]
